[package]
name = "alure"
description = "AluVM runtime environment"
version = "0.1.0"
authors = ["Dr Maxim Orlovsky <orlovsky@pandoracore.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/internet2-org/alure"
homepage = "https://lnp-bp.org"
keywords = ["virtual-machine", "eemulator", "functional-programming", "risc"]
categories = ["no-std", "embedded", "compilers", "cryptography", "emulators"]
readme = "README.md"
exclude = [".github", "test"]

[lib]
name = "alure"

[dependencies]
amplify = "3.6.2"
paste = "1"

[features]
default = []
all = ["std"]
std = ["amplify/std"]
