[package]
name = "aluvm"
description = "AluVM rust implementation"
version = "0.3.0-beta"
authors = ["Dr Maxim Orlovsky <orlovsky@pandoracore.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/internet2-org/rust-aluvm"
homepage = "https://lnp-bp.org"
keywords = ["virtual-machine", "emulator", "declarative", "risc"]
categories = ["no-std", "embedded", "compilers", "cryptography", "emulators"]
readme = "README.md"
exclude = [".github", "test"]

[lib]
name = "aluvm"

[dependencies]
amplify_num = "0.1.2"
amplify_derive = "2.7.1"
paste = "1"
bitcoin_hashes = { version = "0.9.6", default-features = false } # this is most well-maintained generic hash implementation library
secp256k1 = { version = "0.20.2", optional = true }
curve25519-dalek = { version = "3.1", optional = true }
rustc_apfloat = "0.1.3"
half = "1.7.1"

[features]
default = []
all = ["std", "secp256k1", "curve25519"]
std = ["amplify_num/std", "amplify_num/hex", "bitcoin_hashes/std", "secp256k1/std", "curve25519-dalek/std", "curve25519-dalek/alloc"]
curve25519 = ["curve25519-dalek"]
