[package]
name = "aluvm"
description = "Functional registry-based RISC virtual machine"
version = "0.10.2"
authors = ["Dr Maxim Orlovsky <orlovsky@ubideco.org>"]
repository = "https://github.com/aluvm/rust-aluvm"
homepage = "https://aluvm.org"
keywords = ["virtual-machine", "emulator", "functional", "risc", "edge-computing"]
categories = ["no-std", "embedded", "compilers", "cryptography", "emulators"]
rust-version = "1.66" # Due to strict encoding library (caused by GAD)
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
exclude = [".github"]

[lib]
name = "aluvm"

[[bin]]
name = "aluvm-stl"
required-features = ["stl"]

[[example]]
name = "asm"
required-features = ["all"]

[dependencies]
amplify = { version = "4.0.0", default-features = false, features = ["apfloat", "derive", "hex"] }
paste = "1"
strict_encoding = { version = "2.2.0", default-features = false, features = ["float", "derive"] }
strict_types = { version = "1.2.0", optional = true }
sha2 = "0.10.6"
ripemd = "0.1.3"
baid58 = "0.3.1"
secp256k1 = { version = "0.27.0", optional = true, features = ["global-context"] }
curve25519-dalek = { version = "3.2", optional = true }
half = "2.1.0"
serde_crate = { package = "serde", version = "1", optional = true }

[features]
default = ["std"]
all = ["stl", "std", "secp256k1", "curve25519", "serde"]
stl = ["strict_types/base64", "std"]
std = ["amplify/std"]
curve25519 = ["curve25519-dalek"]
serde = ["serde_crate", "amplify/serde", "std"]

[package.metadata.docs.rs]
features = [ "all" ]

[patch.crates-io]
strict_types = { git = "https://github.com/strict-types/strict-types" }
