[package]
name = "alure"
description = "AluVM runtime environment"
version = "0.1.0"
authors = ["Dr Maxim Orlovsky <orlovsky@pandoracore.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/internet2-org/alure"
homepage = "https://lnp-bp.org"
keywords = ["virtual-machine", "eemulator", "functional-programming", "risc"]
categories = ["no-std", "embedded", "compilers", "cryptography", "emulators"]
readme = "README.md"
exclude = [".github", "test"]

[lib]
name = "alure"

[dependencies]
amplify_num = "0.1"
amplify_derive = "2.7.1"
paste = "1"
bitcoin_hashes = "0.9.6" # this is most well-maintained generic hash implementation library

[features]
default = []
all = ["std"]
std = ["amplify_num/std", "amplify_num/hex"]
