[package]
name = "aluvm"
description = "AluVM rust implementation"
version = "0.6.0"
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/internet2-org/rust-aluvm"
homepage = "https://aluvm.org"
keywords = ["virtual-machine", "emulator", "functional", "risc", "edge-computing"]
categories = ["no-std", "embedded", "compilers", "cryptography", "emulators"]
readme = "README.md"
exclude = [".github"]

[lib]
name = "aluvm"

[dependencies]
amplify = { version = "3.12.0", default-features = false, features = ["apfloat", "derive", "hex"] }
paste = "1"
strict_encoding = { version = "1.8.7", default-features = false, features = ["float", "derive"], optional = true }
bitcoin_hashes = { version = "0.10.0", default-features = false } # this is most well-maintained generic hash implementation library
bech32 = { version = "0.9.0", default-features = false }
secp256k1 = { version = "0.22.1", optional = true, features = ["global-context"] }
curve25519-dalek = { version = "3.1", optional = true }
half = "1.7.1"

[features]
default = []
all = ["std", "secp256k1", "curve25519", "strict_encoding"]
std = ["amplify/std", "bitcoin_hashes/std", "secp256k1/std", "curve25519-dalek/std", "curve25519-dalek/alloc", "bech32/std"]
curve25519 = ["curve25519-dalek"]
